# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-Widget-Constraint-ComplexPassword
version:      0.01
version_from: lib/HTML/Widget/Constraint/ComplexPassword.pm
installdirs:  site
requires:
    HTML::Widget::Constraint:      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
